name = "Immersive Vanilla"
author = "Quyet"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0af9c4a87fcd59bfddcf7d3b33e243d5a04264fc7c9a33e277ee675dc71d1af4"

[versions]
fabric = "0.19.3"
minecraft = "1.21.1"
