name = "Immersive Vanilla"
author = "Quyet"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6b490ba822b1939683207b68aa7531ba2701ed25f74dfff24527cf6bbf3dcb09"

[versions]
fabric = "0.19.3"
minecraft = "1.21.1"
