name = "Sea Salt Vanilla"
author = "Quyet"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "54e2152e6547b763cafe4f0e7511aa5e90e18d11bc7d71f7720ecead7ce12a3f"

[versions]
fabric = "0.19.3"
minecraft = "1.21.1"
